language = "cpp"

namespace = "torustiq_common"

include_guard = "_TORUSTIQ_COMMON_H_"

[export]


include = [
    "ModuleInfo",
    "ModulePipelineStepConfigureArgs", "ModuleStepConfigureFnResult",

    "StepStartFnResult",
    "ModuleProcessRecordFnResult",
    
    "ConstCStrPtr",

    "PipelineStepKind",
]

[parse.expand]
all_features = true