language = "cpp"

namespace = "torustiq_common"

include_guard = "_TORUSTIQ_COMMON_H_"

[export]


include = [
    "ModuleInfo",
    "ModulePipelineConfigureArgs", "ModulePipelineConfigureFnResult",

    "StepStartFnResult",
    "ModulePipelineProcessRecordFnResult",
    
    "ConstCStrPtr",

    "PipelineModuleKind",
]

[parse.expand]
all_features = true