language = "c"

include_guard = "_TORUSTIQ_COMMON_H_"

[export]


include = [
    "ModuleInfo",
    "ModulePipelineStepConfigureArgs", "ModuleStepConfigureFnResult",

    "StepStartFnResult",
    "ModuleProcessRecordFnResult",
    
    "ConstCStrPtr",

    "PipelineStepKind",
]

prefix = "torustiq_common_"

[parse.expand]
all_features = true


[enum]
prefix_with_name = true