language = "c"

include_guard = "_TORUSTIQ_COMMON_H_"

[export]


include = [
    "ModuleInfo",
    "ModulePipelineConfigureArgs", "ModulePipelineConfigureFnResult",

    "StepStartFnResult",
    "ModulePipelineProcessRecordFnResult",
    
    "ConstCStrPtr",

    "PipelineModuleKind",
]

prefix = "torustiq_common_"

[parse.expand]
all_features = true


[enum]
prefix_with_name = true